apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: strimzi
  namespace: argocd
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    name: in-cluster
    namespace: development
  project: default
  source:
    chart: strimzi
    helm:
    repoURL: https://strimzi.io/charts/
    targetRevision: 0.8.2
  syncPolicy:
    automated:
      prune: true
      selfHeal: true